export const team = [
  {
    name: 'Awais Nazir',
    role: 'Backend Engineer',
    image: '/team/awais.png',
    github: 'https://github.com/awaisnazir',
    linkedin: 'https://linkedin.com/in/awaisnazir',
    bio: 'A passionate backend developer and software engineering student at UET Lahore. Specialized in Python, Java, C++, and DBMS.',
    skills: ['Python', 'PostgreSQL', 'C++', 'Django', 'Java'],
    cvUrl: '/cv/awais.pdf',
  },
  {
    name: 'Sadam Barkat',
    role: 'Data Analyst',
    image: '/team/sadam.png',
    github: 'https://github.com/sadam-barkat',
    linkedin: 'https://www.linkedin.com/in/sadam-barkat/',
    bio: 'Computer science student at GC University Faisalabad. Enthusiastic about data visualization, analysis, and big data technologies.',
    skills: ['Python', 'Pandas', 'PowerBI', 'SQL'],
    cvUrl: '/cv/sadam.pdf',
  },
  {
    name: 'Sikandar Hussain',
    role: 'AI/ML Engineer',
    image: '/team/sikandar.png',
    github: 'https://github.com/Sikandarh11',
    linkedin: 'https://www.linkedin.com/in/sikandar-hussain-956b3a253/',
    bio: 'Computer engineering student at NUST EME. Deep learning, AI/ML model building, and research are his expertise.',
    skills: ['TensorFlow', 'PyTorch', 'NLP', 'ML Ops'],
    cvUrl: '/cv/sikander.pdf',
  },
]
